role: "Agent"
service:
  ports:
    - name: prom-exporter
      port: 9090
      protocol: TCP
customConfig:
  data_dir: /vector-data-dir
  timezone: "local"
  sources:
    k8s_logs:
      type: kubernetes_logs
      glob_minimum_cooldown_ms: 500
  sinks:
    loki:
      type: loki
      encoding: 
        codec: json
      batch: 
        timeout_secs: 60
      inputs:
        - k8s_logs
      endpoint: http://<LOKI_SVC_NAME>.<NAMESPACE>.svc:3100
      labels:
         cluster_name: <cluster_name>
         container_name: "{{`{{ kubernetes.container_name }}`}}"
         pod_name: "{{`{{ kubernetes.pod_name }}`}}"
         namespace: "{{`{{ kubernetes.pod_namespace }}`}}"
         message: "{{`{{ message }}`}}"